---
bibliography: C:/Users/Michael Andreae/Dropbox/References/K01_bibliography_7Feb15.bib
csl: apa.csl
output:
  pdf_document:
    keep_tex: true
---

# Research Plan
## Significance
### Clincial Impact
##### Acute respiratory failure is a significant burden of disease.
Many hospitalized patients develop acute respiratory failure [@shinystan], which is worrisome.

### Hierarchical modeling better exploits the rich heterogeneity of electronic medical records
##### Electronic medical records are an eminent example of Big Data. 
EMR have more useful data than can be analyzed more useful data than can be analyzed in a scientifically meaningful way by existing statistical inference tools. This limiting the scientific hypotheses and clinical inferences, that can be explored and evaluated. Large electronic medical data sets are not just bigger in that there are more instances of the same thing, (this would make data analysis only easier). Rather, there is more breadth to the data: more subgroups, locations, or time granularity than is currently being modeled, more partial and noisy measurements that cannot easily be incorporated into standard models, more information on the population units being measured, and more fine-grained information on the predictions desired. EMR are the prime example of richly structured and correlated web of data.

##### Big data like electronic medical records are nested hierarchically.
Clinical observations are nested within patients, e.g. repeated glucose measurements will be similar in the same patients. Patients seen by the same provider will have similar outcomes predicted by provider behavior and qualities. Providers are integrated in institutions. Institutions are nested geographically in counties and regions. Healthcare environments predict patient and provider behavior and outcomes. Patients seen by the same team, treated in the same setting will have similar propensity to respond to interventions. Big data requires more than just fitting well-known models at larger scales; it requires richer models to exploit fine-grained multilevel structures and to map to predictive questions of interest.

##### Bayesian hierarchical modeling of complex Big Data is transformative.
With its flexibility and robustness Bayesian models may predict better in large data sets with spatial and temporal organization, than classical models [@Gelman_red_2009].  Consider our multilevel electronic medical records dataset consisting of repeated visits by patients with different ages and medical conditions in different services integrated in different hospitals in different states with different medical plans. Fitting the predictive regression model, we would want the regression coefficients to vary by group (by service, by medical unit, by hospital), to realistically model the complex correlations seen in actual clinical practice: The number of parameters to estimate grows very quickly and so do the potential interactions. Reciprocally, even with very large datasets, the sample size in each subgroup will shrink rapidly; estimates using least squares or maximum likelihood will become noisy and thus often become essentially useless. Regardless, we  will want to estimate various hyperparameters and hyper-hyperparameters, to represent how lower level parameters vary across different groupings [@Bafumi_Gelman_2007].

##### “Partial pooling” outperforms the no-pooling and complete-pooling alternatives.
Hierarchical modeling is more efficient, as can be shown mathematically or via cross-validation [@Gelman-Hill_2014]. "No pooling"" is one approach to estimate the model for each group separately. Addressing and exploring the complexity and granularity, the richness of the data may lead to far too many subclassifications, thus too small samples in any given subgroup for useful inferences. "Complete pooling" or structural modeling is another approach, but the implied hard constraints on the coefficients in different groups may lead to bias, in particular for groups with sparse data; we loose information, because we cannot learn from groups where we have more data. In hierarchical modeling, the estimate of each individual parameter is simultaneously informed by data from all the other units; this is what makes "partial pooling" or hierarchical modeling especially effective [@Gelman_multilevel_2006]. 

#### Heterogeneous provider compliance and incomplete clinical data may limit implementation.
Variables with strong predicitive power in our model may not be recorded in all patients or may be missing for the time window needed for prediction, limiting development of the prediction algorithm, implementation of the therapeutic interventions and the trial itself. To improve prediction for cases with incomplete data, we can impute the missing data. Informative loss by incomplete data may bias risk prediction or may hamper the implementation of the prediction algorithm. Likelihood-based mixed effects models for incomplete data give valid estimates if and only if the data are ignorably missing; that is, the parameters for the missing data process are distinct from those of the main model for the outcome, and the data are missing at random (MAR) [@Rubin_1976]. However, this is an unreasonable assumption for our electronic medical records, for example because physicians will request test based on the patients comorbidities and current clinical conditions. Data will not be missing at random, instead incomplete data will be associated with predictors and outcomes.

##### Developing new Bayesian methods for imputation of incomplete data from auxilliary data.
Auxilliary date are additional information available in the form of variables known to be correlated with the missing data of interest. For example, arterial blood gas oxygen saturation may be used to impute peripheral pulse oxymetry or oxygen therapy, if the latter are unavailable for the prediction time window, and vice versa. This appraoch avoids the perils associated with missing at random (MAR) assumptions, when fitting a non-ignorable missingness model [@Wang_20029935]. Adding auxiliary variables not included in the main model for multiple imputation, in other words using additional information that is correlated with the missing outcome is an emerging approach to help correct bias [@Meng_1994; @Collins_11778676; @Rubin_1996], often relying on Bayesian methods for the multiple imputations approach [@Daniels_2008; @Schafer_1997]; joint modeling and multiple imputations could both be used also to impute incomplete medical records [@Fitzmaurice_2008]. The use of auxiliary data to impute incomplete patient records will improve the prediction model and facilitate smoother implementation of the algorithm into the clinical trial [@Hall_25389642]. Moreover, auxilliary data imputation for incomplete electronic medical records is underdeveloped; methodologically, their development is an innovative hallmark of this proposal.

# References